services:
  dozzle:
    image: amir20/dozzle:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.dozzle.rule=Host(`${DOZZLE_HOST}`)
      - traefik.http.routers.dozzle.entrypoints=websecure
      - traefik.http.routers.dozzle.tls.certresolver=tailscale
      - traefik.http.routers.dozzle.middlewares=${TRAEFIK_AUTH_MIDDLEWARE}
      - traefik.http.services.dozzle.loadbalancer.server.port=8080
