services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    volumes:
      - ${DATA_DIR}/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.rule=Host(`${HOMEPAGE_HOST}`)
      - traefik.http.routers.homepage.entrypoints=websecure
      - traefik.http.routers.homepage.tls.certresolver=tailscale
      - traefik.http.routers.homepage.middlewares=${TRAEFIK_AUTH_MIDDLEWARE}
      - traefik.http.services.homepage.loadbalancer.server.port=3000
